version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-capstone
    depends_on:
      - postgres
      - redis
    environment:
      HOST: "http://localhost:3000"
      PORT: 3000
      CORS: "*"
      POSTGRES_URL: "postgresql://root:root@postgres-capstone:5432/capstone?schema=public"
      REDIS_URL: "redis://redis-capstone:6379"
      JWT_SECRET: "secret"
      JWT_EXPIRED_TIME: "1h"
      NEBIUS_QWEN_API_KEY: "xxx"
      NEBIUS_DEEPSEEK_API_KEY: "xxx"
      RESEND_API_KEY: "xxx"
    ports:
      - "3000:3000"
    networks:
      - capstone_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-capstone
    depends_on:
      - backend
      - frontend
    ports:
      - "4000:80"
    networks:
      - capstone_network

  postgres:
    image: postgres:15
    container_name: postgres-capstone
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: capstone
    ports:
      - "5432:5432"
    networks:
      - capstone_network

  redis:
    image: redis:7-alpine
    container_name: redis-capstone
    restart: always
    ports:
      - "6379:6379"
    networks:
      - capstone_network

  ml:
    # warning! build can take longer time, as it required bigger library ex: tensor flow to be download
    # and the container size can exceed 2GB+
    # build:
    #   context: ./ML
    #   dockerfile: Dockerfile

    # instead can pull and use image that has been build by author
    image: wisnup001binus/ml_capstone:1.0

    container_name: ml-capstone
    environment:
      HOST: "0.0.0.0"
      PORT: 80
    ports:
      - "3005:80"
    networks:
      - capstone_network

  nginx:
    container_name: nginx-router-capstone
    build:
      context: ./"nginx router"
      dockerfile: Dockerfile
    ports:
      - "1000:80"
    networks:
      - capstone_network
    
networks:
  capstone_network:
    driver: bridge
